### ISSUE TITLE
False import of Cryptodome library

### ISSUE THREAD

**Issue by whoot** [akabe1/kr00ker#3]
Hello,

it seems that you did not correctly import the cryptodome library.
Instead of using `from Cryptodome.Cipher import AES` you have to use `from Crypto.Cipher import AES`, otherwise it does not work with Python3 and you get the following error message:

![grafik](https://user-images.githubusercontent.com/8066322/104164110-babe6700-53f7-11eb-896f-cbf73f70b9d4.png)

Regards

**Comment by akabe1** [comment]
Sorry for the delay. It could be a issue on your python environment, the script works correctly on python3 with Cryptodome:
![Screenshot from 2021-06-08 14-30-39](https://user-images.githubusercontent.com/46047144/121185906-d45cc100-c866-11eb-9751-f30000830aca.png)
